# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parsequic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parsequic.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z)github.com/TOMOFUMI-KONDO/parsequic/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fparsequic.proto\x12\x05proto\" \n\x10ParseQuicRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"~\n\x0eParseQuicReply\x12\x14\n\x0cisLongHeader\x18\x01 \x01(\x08\x12\x1f\n\x04type\x18\x02 \x01(\x0e\x32\x11.proto.PacketType\x12\x0f\n\x07version\x18\x03 \x01(\r\x12\x11\n\tdstConnID\x18\x04 \x01(\x0c\x12\x11\n\tsrcConnID\x18\x05 \x01(\x0c*g\n\nPacketType\x12\x0b\n\x07ONE_RTT\x10\x00\x12\x17\n\x13VERSION_NEGOTIATION\x10\x01\x12\x0b\n\x07INITIAL\x10\x02\x12\x0c\n\x08ZERO_RTT\x10\x03\x12\r\n\tHANDSHAKE\x10\x04\x12\t\n\x05RETRY\x10\x05\x32\x46\n\tParseQuic\x12\x39\n\x05Parse\x12\x17.proto.ParseQuicRequest\x1a\x15.proto.ParseQuicReply\"\x00\x42+Z)github.com/TOMOFUMI-KONDO/parsequic/protob\x06proto3'
)

_PACKETTYPE = _descriptor.EnumDescriptor(
  name='PacketType',
  full_name='proto.PacketType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ONE_RTT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERSION_NEGOTIATION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INITIAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ZERO_RTT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HANDSHAKE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RETRY', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=188,
  serialized_end=291,
)
_sym_db.RegisterEnumDescriptor(_PACKETTYPE)

PacketType = enum_type_wrapper.EnumTypeWrapper(_PACKETTYPE)
ONE_RTT = 0
VERSION_NEGOTIATION = 1
INITIAL = 2
ZERO_RTT = 3
HANDSHAKE = 4
RETRY = 5



_PARSEQUICREQUEST = _descriptor.Descriptor(
  name='ParseQuicRequest',
  full_name='proto.ParseQuicRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.ParseQuicRequest.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=58,
)


_PARSEQUICREPLY = _descriptor.Descriptor(
  name='ParseQuicReply',
  full_name='proto.ParseQuicReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isLongHeader', full_name='proto.ParseQuicReply.isLongHeader', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.ParseQuicReply.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='proto.ParseQuicReply.version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dstConnID', full_name='proto.ParseQuicReply.dstConnID', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='srcConnID', full_name='proto.ParseQuicReply.srcConnID', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=186,
)

_PARSEQUICREPLY.fields_by_name['type'].enum_type = _PACKETTYPE
DESCRIPTOR.message_types_by_name['ParseQuicRequest'] = _PARSEQUICREQUEST
DESCRIPTOR.message_types_by_name['ParseQuicReply'] = _PARSEQUICREPLY
DESCRIPTOR.enum_types_by_name['PacketType'] = _PACKETTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParseQuicRequest = _reflection.GeneratedProtocolMessageType('ParseQuicRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARSEQUICREQUEST,
  '__module__' : 'parsequic_pb2'
  # @@protoc_insertion_point(class_scope:proto.ParseQuicRequest)
  })
_sym_db.RegisterMessage(ParseQuicRequest)

ParseQuicReply = _reflection.GeneratedProtocolMessageType('ParseQuicReply', (_message.Message,), {
  'DESCRIPTOR' : _PARSEQUICREPLY,
  '__module__' : 'parsequic_pb2'
  # @@protoc_insertion_point(class_scope:proto.ParseQuicReply)
  })
_sym_db.RegisterMessage(ParseQuicReply)


DESCRIPTOR._options = None

_PARSEQUIC = _descriptor.ServiceDescriptor(
  name='ParseQuic',
  full_name='proto.ParseQuic',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=293,
  serialized_end=363,
  methods=[
  _descriptor.MethodDescriptor(
    name='Parse',
    full_name='proto.ParseQuic.Parse',
    index=0,
    containing_service=None,
    input_type=_PARSEQUICREQUEST,
    output_type=_PARSEQUICREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARSEQUIC)

DESCRIPTOR.services_by_name['ParseQuic'] = _PARSEQUIC

# @@protoc_insertion_point(module_scope)
